### ISSUE TITLE
Rails 5 Compatibility

### ISSUE THREAD

**Issue by cyri113** [stevehodges/draftpunk#3]
Hi Steve - I just tried to get this gem running on Rails 5. Unfortunately it was unsuccessful. Is it the question of updating references or is there a deeper issue? Thank you.

**Comment by stevehodges** [comment]
0.2.6 appears to function with rails 5.0.2. There's a bunch of deprecation warnings, one of which I've fixed on 0.2.7. I also fixed 2 broken tests in the gem, so tests should pass again.

One deprecation warning is due to an open issue in the unscoped_associations gem (https://github.com/markets/unscoped_associations/issues/16), which hopefully they'll address before 5.1 is released.
