### ISSUE TITLE
keep old versions

### ISSUE THREAD

**Issue by ghost** [stevehodges/draftpunk#6]
I'm trying to figure out a way to keep my old published versions.  I'm trying to have a kind of history of the published versions.

Is it something you think can be added to draftpunk or is it too far away from its original purpose?

**Comment by stevehodges** [comment]
I could see this as a feature of _draft_punk_, though there are a few gems that, used with _draft_punk_, might accomplish what you're looking for:

I use [audited-activerecord](https://github.com/collectiveidea/audited) in conjunction with _draft_punk_ to track changes to models. It adds database inserts every time you change the model, containing a diff of what changed. Then you can step through the versions to view a prior version. It supposedly works with associated objects, too.

I also have used [paranoia](https://github.com/rubysherpas/paranoia), which doesn't destroy database object (it instead flags them as deleted). This would leave them in the db if you simply want to keep them around (i.e. when the draft is approved).

If your request were implemented in _draft punk_, there would be a join table to associate a Post with its previously-approved posts. (I'd add a Rails generator to allow you to add a join table, i.e. `post_versions`). `Post.find(20).previous_versions` would return an array of previously-approved posts, complete with their associations at that time.

The real cost is database size - you are storing a complete copy of that post and its associations for each version. Example:

Post #20 has these associated objects:
- 4 categories (through the join table `categories_posts`)
- 8 images
- 1 author (not approvable)

Creating a draft adds a new post object (Post 21), plus 4 categories_posts and 8 images. So, 13 objects added to the database.

If Post 21 has 10 approved versions in its history, and all 10 have the same # of associations, there are:

- 130 objects for the history (12 + 1 post) x 10
- 10 `post_versions`
- 28 objects (for the current approved version and its draft)

For a total of 168 objects. Depending on your needs, it could be worthwhile to keep that around, and _draft_punk_ users would certainly be able to switch it on if they want.

**Comment by ghost** [comment]
It makes sense what you said above. 

Maybe another way to do it instead of having a join table would be to store a reference on the same table (as you do now) and to store the `draft_version_id` on top of the `approved_version_id` (to be retro-compatible).

In this case we would have something like this for the `posts` table :

``` ruby
post = Post.create(name: 'My new post')
```

id | name | draft_version_id
---- | ---- | ----
1 | My new post | nil

``` ruby
post
post.approve!
```

id | name | draft_version_id
---- | ---- | ----
1 | My new post | nil
2 | My new post | 1

``` ruby
p post.id
# 1

p post.approved_version.id
# 2

post.update(name: 'Some other name')
```

id | name | draft_version_id
---- | ---- | ----
1 | Some other name | nil
2 | My new post | 1

``` ruby
post.approve!
```

id | name | draft_version_id
---- | ---- | ----
1 | Some other name | nil
2 | My new post | 1
3 | Some other name | 1


``` ruby
p post.approved_version.id
# 3 <- looks for the the Post where the the current post is a draft

p post.approved_versions.map &:id
# [3, 2] <- sorting from newer to older ones

p Post.find(3).draft_version.id
# 1

p Post.find(2).draft_version.id
# 1

p Post.find(2).approved_version.id
# 3
```

On a side note, this could allow us to start a draft from any moment in time by simply doing a .dup of an approved version and then removing it's `draft_version_id`.

Regarding the database space, I think that if your project needs to have version history this is kind of something we can't solve. I would even argue that it should stay like that.

For us the trade-off is worth it

**Comment by ghost** [comment]
Hi @stevehodges, do you have any news on this issue?

**Comment by stevehodges** [comment]
I like your suggestion to store an array of the version history, though support for that will vary depending on the database driver. In addition to adding the feature, I'm also adding tests to ensure the gem works for each driver.

**Comment by stevehodges** [comment]
@sayduck-daniel I neglected to mention that I'm actively working on the database driver tests... so hopefully I'll have this wrapped up shortly.

**Comment by ghost** [comment]
Are you actually gonna store the array in a database column? Couldn't that be achieve by using a has_many association added by the gem directly, like `has_many :approved_versions, class_name: klass, foreign_key: :approved_version_id`?

I'm not familiar with Gem development, but let me know how I can help.

**Comment by stevehodges** [comment]
Yes, I'm storing the array in the column so you can query for all of the old published versions in one SQL query.

If a post has a column approved_version_history_ids, you can find all of them in one fast query (complexity is o<sup>1</sup>):

    post.id => 4
    post.approved_version_history_ids => [5,6,7]
    Post.where(id: approved_version_history_ids) => select * from posts where id IN (5,6,7);

Your most recent suggestion is a self-referential join. It's definitely an option and takes slightly less space in the db, but you can only query for them one at a time. 

    post.id => 4
    post.approved_version_id => 7
    previous_version = post.previous_version => select * from posts where id = 7;
    previous_version.approved_version_id => 6
    another_previous_version = previous_version.previous_version => select * from posts where id = 6;

Since the post only refers to the previous version, it's efficient to store, but inefficient to query them all. (complexity is o<sup>n</sup>).

**Comment by stevehodges** [comment]
> Are you actually gonna store the array in a database column? Couldn't that be achieve by using a has_many association added by the gem directly, like has_many :approved_versions, class_name: klass, foreign_key: :approved_version_id?

That probably makes the most sense, yes. I was thinking you were suggesting storing the previously-approved version's id, forming a linked-list of sorts.

**Comment by ghost** [comment]
I'm a bit lost now.

What I was initially thinking is:
- we would have 1,1 "draft" version at any moment.
- we would have 0,n "approved" versions at any moment.

And to achieve that, what I was thinking to implement is:
- the first "version" would always be the draft
- when we approve, we dup and reference the draft on that new object. (Like that, publishing doesn't change the draft at all)

To illustrate, let's take this scenario:

1) Create my business with the name `Foo`

        id | name | draft_version_id
        ---|------|--------------------
         1 | Foo  | nil 

1) Publish it

        id | name | draft_version_id
        ---|------|--------------------
         1 | Foo  | nil 
         2 | Foo  | 1

1) Change the name to `Bar`

        id | name | draft_version_id
        ---|------|--------------------
         1 | Bar  | nil 
         2 | Foo  | 1

1) Publish it

        id | name | draft_version_id
        ---|------|--------------------
         1 | Bar  | nil 
         2 | Foo  | 1
         3 | Bar  | 1

1) Change the name to `Baz` (not publish yet)
        id | name | draft_version_id
        ---|------|--------------------
         1 | Baz  | nil 
         2 | Foo  | 1
         3 | Bar  | 1

We should have the methods:
```ruby
def draft_version?
  draft_version_id.blank?
end

Business.find(1).draft_version? # true
Business.find(2).draft_version? # false
Business.find(3).draft_version? # false
````

```ruby
def approved_version?
  !draft_version
end

Business.find(1).approved_version? # false
Business.find(1).approved_version? # true
Business.find(1).approved_version? # true
````

```ruby
def draft_version
  Business.find(draft_version_id || id)
end

Business.find(1).draft_version.id # 1
Business.find(2).draft_version.id # 1
Business.find(3).draft_version.id # 1
```

```ruby
def approved_versions
  Business.where('draft_version_id IN [?, ?]`, draft_version_id, id)
end

# approved_versions -> would return an ActiveRecord Association and not ids
Business.find(1).approved_versions # [2, 3]
Business.find(2).approved_versions # [2, 3]
Business.find(3).approved_versions # [2, 3]
````

```ruby
def latest_approved_version
  approved_versions.last
end

Business.find(1).latest_approved_version.id # 3
Business.find(2).latest_approved_version.id # 3
Business.find(3).latest_approved_version.id # 3
```

I thing with this method, we could keep it working with all ORM (as we would be using rails belongs_to and has_many relations).

Frosting on the cake: this would even allow us to even fork any approved_version to a new draft and start from there again.

**Comment by stevehodges** [comment]
Maybe this will help clarify any confusion:

A primary requirement of draftpunk is that the approved version is never deleted - its id never changes - it is canonical. This means that if you use typical Rails routing, the path to that approved version never changes. If you have a blog post that's at /posts/1, it will always be at /posts/1 regardless of the number of times it is approved. In my domain, we need to store audits of each change for regulatory compliance. Those audits are associated with the approved version. Regardless of the number of times it is approved, the audits reflect what changes were made to the approval over the life of that "post".

So, that means (in this gem) the draft can be destroyed at any point - the approved version cannot.

The draft is destroyed because, when you approve a post, draftpunk updates all the draft's associations and reassociates them with the approved version. If the draft is Post 2 and had 32 images associated with it, those images all had post_id 2. During approval, draft_punk updates them to be associated with Post 1 in a single SQL query. This is a lot faster than recreating 32 objects. This was a design decision; either approving or creating a draft was going to be slower. We opted for faster approvals.

Regarding the change at hand (which is almost done). First, I've switched back to using a standard rails association (no storing of array of IDs) as you're right, it's the most expected and rails-y approach.The interface is pretty much as you describe, returning an activerecordrelation.

The primary change: when a draft (post 2)  is approved, first I duplicate the approved version, storing it as Post 3. Then, the approved version is updated like normal (and the draft destroyed). We end up with two posts i the database; post 1 (our canonical approved version) and post 3 , our archive - the previously approved version.

The frostings on the cake still work. I am currently working on promoting an old approved version to be the current approved version, and there's the potential to be able to fork - promote an old approved version to be a new canonical version with its own drafts.

**Comment by ghost** [comment]
Ok, got it.

I think something that could be error prone is the "change of ids" in the approved_versions history

```ruby
Post.find(1).approved_versions.first # 1
draft = Post.find(1). editable_version
draft.publish_draft!
Post.find(1).approved_versions.first # 3
Post.find(1).approved_versions.second # 1
```

In my company's scenario, we need to always keep an open draft. I will then override the `publish_draft!` method to do a `editable_version` as well.

**Comment by stevehodges** [comment]
I've pushed this to master but have not yet published a new version of the gem. Per the (updated) README:

> To enable this feature, add a `current_approved_version_id` column (Integer) to the model you call requires_approval on. Version history will be automatically tracked if that column is present.

If you want to test this in your app before I publish the gem, add this to your Gemfile:

    gem 'draft_punk', git: 'https://github.com/stevehodges/draftpunk.git'

There's also a method to allow you to promote a historic version to be the current approved version - `post.make_current!`.

If you instead wanted to make that a NEW post (no longer associated with its current approved version), you could simply just set `current_approved_version_id` to nil, and you now have a standalone, approved object.

**Comment by ghost** [comment]
thank you @stevehodges, I'm gonna try this next week most probably. Any idea when the gem is gonna be published?

**Comment by stevehodges** [comment]
Version 0.3.0 of the gem is available on RubyGems. If you run into any issues or have feature requests, please open another issue. Thanks!
